# Generated by Django 5.0.7 on 2024-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_product_digital"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
