# Generated by Django 5.0.7 on 2024-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_product_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
